## Importações das bibliotecas:

In [1]:
#Importações:
import numpy as np #Biblioteca de Algebra linear
import sklearn #Biblioteca de Machine Learning
import warnings
warnings.filterwarnings('ignore')
from numpy import genfromtxt #Biblioteca para mexer nos arquivos da aula(Q n serão imagens)



```
O Comando a seguir é para baixar dados da internet pelo código,
ou seja, sobretudo tratando-se de colab, é um comando muito importando.
```



## Importação dos dados:

In [2]:
#Baixando os dados direto do link do site! - Também funciona no jupyter:
!wget https://archive.ics.uci.edu/ml/machine-learning-databases/00267/data_banknote_authentication.txt

--2022-11-09 16:16:24--  https://archive.ics.uci.edu/ml/machine-learning-databases/00267/data_banknote_authentication.txt
Resolving archive.ics.uci.edu (archive.ics.uci.edu)... 128.195.10.252
Connecting to archive.ics.uci.edu (archive.ics.uci.edu)|128.195.10.252|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 46400 (45K) [application/x-httpd-php]
Saving to: ‘data_banknote_authentication.txt.1’

data_banknote_authe 100%[===================>]  45.31K  --.-KB/s    in 0.1s    

2022-11-09 16:16:24 (461 KB/s) - ‘data_banknote_authentication.txt.1’ saved [46400/46400]



In [6]:
dados = genfromtxt('data_banknote_authentication.txt', delimiter=',')
dados

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699,   0.     ],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ,   0.     ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645,   0.     ],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ,   1.     ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ,   1.     ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ,   1.     ]])

## Tratamento inicial dos dados:

Os dados fornecidos são um imenso array... Então a
ideia aqui é separar esse array em dois, um contendo
os labels (rótulos/etiquetas) que não nossos resultados
 e features que são nossas informações. 

Esse tratamento inicial é uma coisa que todos os dados que venham nessa forma precisam ser feitos. Por que sempre, para esse tipo de trabalho, precisa-se
dos dados da informação e dos rótulos separadamente.

In [7]:
#Puxando os rótulos
labels = dados[:,4] #Assim, labels será um array apenas com os rótulos.
labels

array([0., 0., 0., ..., 1., 1., 1.])



```
Também não entendi porque ",4", apenas copiei como
o professor copiou. De mesmo modo, puxer-se-irá as 
caracteristicas.
```



In [8]:
#Puxando as caracteristicas:
features = dados[:,0:4]
features

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ]])

In [25]:
#Datasets
X = features #X maiúsculo é sempre o dataset
y = labels #y minúsculo é sempre os rótulos



```
Por fim, temos os datasets divididos e tudo certinho.
```



## Separando os dados:

Os dados precisam ser separados entre dados para treino
e dados para teste, para o melhor funcionamento das
redes neurais.

In [11]:
#Importando a função para a divisão dos dados:
from sklearn.model_selection import train_test_split

In [13]:
#Separando dados para treinamento
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.33,random_state=42)



```
As vezes, os subconjuntos para treino e teste ficam
num escalonamento estranho. Para resolver isso, 
precisa-se passar os dados de treino e teste por um
tratamento específico.
```



## Reprocessando os dados:

Não é algo essencial para esses dados, mas é uma
boa prática, pois dados datasets maiores precisam ser
normalizados para terem menor custo computacional.

In [19]:
#Importando a função para o reprocessamento dos dados:
from sklearn.preprocessing import MinMaxScaler

In [20]:
#Reprocessando os dados:
scaler_object = MinMaxScaler()

In [21]:
scaler_object.fit(X_train)
scaler_object.fit(X_test)

MinMaxScaler()

In [34]:
scaled_X_train = scaler_object.transform(X_train)
scaled_X_test = scaler_object.transform(X_test)

In [23]:
X_train.max()

17.9274

In [35]:
scaled_X_train.max()

1.0699290780141841



```
A ideia desse reprocessamento dos datasets é ganho de
performance... Nesse caso específico não fará tanta
diferença, mas para datasets maiores, é bom esse
tratamento pra deixar os dados bem comportados.

Ou seja, todo esse processo de scaler_object, fit e
transform nada mais é do que uma boa prática de normalização de dados.
```



## Criando o modelo com Keras:

In [28]:
#Importação das bibliotecas:
from keras.models import Sequential #Cria a rede neural de forma sequenciada
from keras.layers import Dense #Primeira camada de neurónios

### Criação do modelo:

In [31]:
#Criando as variaveis Modelo:
modelo = Sequential() #Criando o modelo Neural

modelo.add(Dense(4, input_dim=4,activation='relu')) #Primeira camada de neuronios
modelo.add(Dense(8,activation='relu')) #Segunda camada de neuronios
modelo.add(Dense(1,activation='sigmoid')) #Teceisa cama de neuronios - Sigmoide pq a saida é 0 ou 1

In [32]:
#Função de custo:
modelo.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

### Treinamento do Modelo:

In [45]:
#Treinando os modelos:
modelo.fit(scaled_X_train, y_train, epochs=50, verbose=2)

Epoch 1/50
29/29 - 0s - loss: 0.1866 - accuracy: 0.9489 - 69ms/epoch - 2ms/step
Epoch 2/50
29/29 - 0s - loss: 0.1821 - accuracy: 0.9489 - 52ms/epoch - 2ms/step
Epoch 3/50
29/29 - 0s - loss: 0.1782 - accuracy: 0.9445 - 52ms/epoch - 2ms/step
Epoch 4/50
29/29 - 0s - loss: 0.1751 - accuracy: 0.9510 - 51ms/epoch - 2ms/step
Epoch 5/50
29/29 - 0s - loss: 0.1703 - accuracy: 0.9445 - 65ms/epoch - 2ms/step
Epoch 6/50
29/29 - 0s - loss: 0.1694 - accuracy: 0.9456 - 50ms/epoch - 2ms/step
Epoch 7/50
29/29 - 0s - loss: 0.1633 - accuracy: 0.9489 - 51ms/epoch - 2ms/step
Epoch 8/50
29/29 - 0s - loss: 0.1593 - accuracy: 0.9510 - 64ms/epoch - 2ms/step
Epoch 9/50
29/29 - 0s - loss: 0.1559 - accuracy: 0.9499 - 50ms/epoch - 2ms/step
Epoch 10/50
29/29 - 0s - loss: 0.1524 - accuracy: 0.9489 - 62ms/epoch - 2ms/step
Epoch 11/50
29/29 - 0s - loss: 0.1490 - accuracy: 0.9499 - 61ms/epoch - 2ms/step
Epoch 12/50
29/29 - 0s - loss: 0.1462 - accuracy: 0.9532 - 51ms/epoch - 2ms/step
Epoch 13/50
29/29 - 0s - loss: 0.1443



```
Cabe aqui lembrar o cuidado com o overfit, para não cagar a previsão.
#Ficaadica ;)
```



In [37]:
#Prevendo:
modelo.predict(scaled_X_test)

15/15 [==============================] - 0s 2ms/step


array([[0.05966152],
       [0.44767478],
       [0.25994447],
       [0.08429745],
       [0.05966247],
       [0.04484829],
       [0.258435  ],
       [0.02795776],
       [0.06062131],
       [0.19219135],
       [0.5362523 ],
       [0.86812687],
       [0.23286161],
       [0.8275458 ],
       [0.72556925],
       [0.23292081],
       [0.92743963],
       [0.93409526],
       [0.89648366],
       [0.87309456],
       [0.02818214],
       [0.12195799],
       [0.8953694 ],
       [0.02384249],
       [0.993186  ],
       [0.03035279],
       [0.02353416],
       [0.8778833 ],
       [0.01623662],
       [0.01917799],
       [0.6805814 ],
       [0.14851011],
       [0.21911909],
       [0.99351424],
       [0.9782118 ],
       [0.02222222],
       [0.5084361 ],
       [0.80957204],
       [0.8823461 ],
       [0.12992947],
       [0.07910293],
       [0.67249423],
       [0.8077772 ],
       [0.03548343],
       [0.98381674],
       [0.8724456 ],
       [0.9551766 ],
       [0.052



```
A saida do predict é um conjunto de probabilidades, no caso, um array
de probabilidades, que de sair a determinada previsão dos dados.

Mas ainda há de se ver a precisão dessa previsão. Pra isso precisa-se:
```



In [41]:
#Checando acuracidade:
predictions = (modelo.predict(scaled_X_test) > 0.5).astype("int32")
predictions

15/15 [==============================] - 0s 3ms/step


array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
    

In [42]:
#Checando métricas:
modelo.metrics_names

['loss', 'accuracy']

In [44]:
#Checando a performance do modelo:
modelo.evaluate(x=scaled_X_test,y=y_test)

15/15 [==============================] - 1s 7ms/step - loss: 0.1844 - accuracy: 0.9492


[0.18437440693378448, 0.9492273926734924]

In [46]:
#Criando recorte de  classificação:
from sklearn.metrics import confusion_matrix,classification_report

In [52]:
predictions = np.argmax(modelo.predict(scaled_X_test), axis=-1)
predictions

15/15 [==============================] - 0s 2ms/step


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,